// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVVKia-o_sgbZeDUe-Hk6bDOZswad5js',
    appId: '1:694173932444:web:6908c6c6b251aacb758659',
    messagingSenderId: '694173932444',
    projectId: 'todolist-fd072',
    authDomain: 'todolist-fd072.firebaseapp.com',
    storageBucket: 'todolist-fd072.firebasestorage.app',
    measurementId: 'G-J8RCYBVZNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJs4SjqYjYBD6C9TgGJRUOWpVrWizIgMw',
    appId: '1:694173932444:android:972a1368b9c1b688758659',
    messagingSenderId: '694173932444',
    projectId: 'todolist-fd072',
    storageBucket: 'todolist-fd072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Ho_ha5Z5mqG0gf30Jq0YbYsBYIzKGdY',
    appId: '1:694173932444:ios:b1108aa142542bb2758659',
    messagingSenderId: '694173932444',
    projectId: 'todolist-fd072',
    storageBucket: 'todolist-fd072.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Ho_ha5Z5mqG0gf30Jq0YbYsBYIzKGdY',
    appId: '1:694173932444:ios:b1108aa142542bb2758659',
    messagingSenderId: '694173932444',
    projectId: 'todolist-fd072',
    storageBucket: 'todolist-fd072.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVVKia-o_sgbZeDUe-Hk6bDOZswad5js',
    appId: '1:694173932444:web:3a4d12a959093ccb758659',
    messagingSenderId: '694173932444',
    projectId: 'todolist-fd072',
    authDomain: 'todolist-fd072.firebaseapp.com',
    storageBucket: 'todolist-fd072.firebasestorage.app',
    measurementId: 'G-NZ3DYBLYYP',
  );
}
